service: aws-node-typescript-apollo-lambda

frameworkVersion: "3"

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 15
  apiGateway: 
    apiKeys:
      - lambdaApolloKey

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          private: true
          path: graphql
          method: post
      - http:
          private: true
          path: graphql
          method: get
