service: aws-node-ses-send-email-and-offline

frameworkVersion: '3'

plugins:
  - serverless-offline-ses-v2
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
          - "ses:SendEmail"
          Resource: "*"

functions:
  sendEmail:
    handler: handler.main
    events:
    - schedule: rate(1 minute)
