service: serverless-ruby-simple-http-endpoint
frameworkVersion: '2'

provider:
  name: aws
  runtime: ruby2.7

functions:
  current_time:
    handler: handler.endpoint
    events:
      - httpApi:
          path: /ping
          method: get
