service: aws-java-simple-http-endpoint
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8

package:
  artifact: build/distributions/aws-java-simple-http-endpoint.zip

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - httpApi:
          path: /ping
          method: get
