service: aws-node-express-api

frameworkVersion: '2'
variablesResolutionMode: '20210219'
configValidationMode: 'error'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  apiGateway:
    shouldStartNameWithService: true

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
