service: replicator

plugins:
  - serverless-lift

constructs:
  inputBucket:
    type: storage
  outputBucket:
    type: storage

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  replicate:
    handler: handler.replicate
    environment:
      OUTPUT_BUCKET: ${construct:outputBucket.bucketName}
    events:
      - s3:
          bucket: ${construct:inputBucket.bucketName}
          existing: true
